dummy_chat_logs:
  "1번 대화":
    conversation:
      - "상대: 오늘 하루 어땠어? 😊"
      - "나: 그냥 평범했지 뭐 ㅎㅎ 너는?"
      - "상대: 나도 뭐~ 근데 왠지 모르게 너랑 톡하면 하루가 좀 더 특별해지는 느낌? 😏"
      - "나: 오~ 오늘은 또 왜 이렇게 말이 스윗해? ㅎㅎ"
      - "상대: 원래도 스윗했는데 너만 몰랐던 거 아냐? 🤭"
      - "나: 아, 맞다! 너 저번에 추천해준 카페 갔다 왔어! 분위기 진짜 좋더라~"
      - "상대: 오! 진짜? 근데 왜 나랑 안 갔어? 섭섭하네 ㅋㅋ"
      - "나: ㅋㅋㅋ 다음에 같이 가자! 그럼 됐지? 😆"
      - "상대: 오케이, 약속했어! 말 바꾸기 없기!"
      - "나: 네네~ 근데 너 뭐 먹었어? 저녁 안 챙겨 먹은 거 아니지?"
      - "상대: 응~ 근데 너 걱정해 주는 거 기분 좋다 😌"
      - "나: 당연하지~ 친구잖아! ㅎㅎ"
      - "상대: …그치, 친구니까 그렇겠지? (뭔가 아쉽네 ㅋㅋ)"
      - "나: ㅋㅋㅋㅋ 뭔가? 왜 말 흐려~"
      - "상대: 아냐아냐~ 그냥… 네가 나한테 하는 말이 썸 같기도 하고, 친구 같기도 하고 헷갈려서 ㅎㅎ"
      - "나: 음… 그럼 내가 좀 더 헷갈리게 해줄까? 😉"
      - "상대: 뭐야ㅋㅋㅋ 궁금한데?"
  "2번 대화":
    conversation:
      - "상대: 뭐해? 😏"
      - "나: 그냥 침대에 누워서 폰 만지고 있어~ 너는?"
      - "상대: 나도 비슷해 ㅋㅋ 근데 너 왜 이렇게 답장이 빠름? 나 기다리고 있었음? 😏"
      - "나: 어이없어 ㅋㅋㅋ 그냥 폰 보고 있다가 바로 온 거지~"
      - "상대: 에이, 그래도 내가 톡 보내니까 바로 답한 거잖아? 나한테 관심 있네~?"
      - "나: 뭔 소리야 ㅋㅋㅋㅋ 말 돌리지 마~"
      - "상대: 그럼 솔직하게 말해봐. 나랑 톡 하는 거 좀 기대했음? ☺"
      - "나: 뭐… 안 그랬다고 하면 거짓말이겠지만? ㅎㅎ"
      - "상대: 헐, 이거 녹음해야겠다. 수진 씨, 지금 마음 살짝 드러난 거 인정하시나요?"
      - "나: 인정 안 함~ 그냥 심심해서 그런 거임 ㅋㅋ"
      - "상대: 치, 실망인데? 난 수진이랑 톡 하는 게 제일 재밌는데~"
      - "나: 오~ 멘트 좋아졌네? 연습했어?"
      - "상대: 너랑 톡 하면서 자연스럽게 업그레이드됨 ㅋㅋ"
      - "나: 그럼 나는? 나도 좀 늘었나?"
      - "상대: 흠… 잘 모르겠는데? 직접 만나서 테스트해 봐야겠는데?"
      - "나: 테스트라니? 뭘 어떻게? ㅋㅋ"
      - "상대: 그러니까… 주말에 같이 밥 먹으면서 대화 실력 좀 체크해보자고~ 😉"
      - "나: ㅋㅋㅋ 갑자기 약속 잡기야?"
      - "상대: 아, 싫으면 그냥 안 해도 됨. 나는 약간 서운하지만 😔"
      - "나: 누가 싫대? 내가 시간 보고 알려줄게 ㅎㅎ"
      - "상대: 오케이! 수진 씨께서 시간을 허락해 주시길 기다리겠습니다~"
      - "나: ㅋㅋㅋㅋ 알았어, 그럼 잘 자~"
      - "상대: 응, 잘 자고 좋은 꿈 꿔~ 나랑 함께하는 꿈? 😏"
      - "나: 아 뭐야~ 오글거려 ㅋㅋㅋㅋ 나 잔다!!"
      - "상대: ㅋㅋㅋ 굿나잇! 😴"
  "3번 대화":
    conversation:
      - "상대: 야, 오늘 날씨 대박이더라?"
      - "나: 맞아! 낮에는 햇살도 따뜻하고, 바람도 살랑살랑~"
      - "상대: 그러니까~ 이런 날은 산책해야 되는데, 나 혼자 걷고 왔다…"
      - "나: 아쉽겠다~ 누가 같이 걸어줄 사람 없었나 보네 ㅋㅋ"
      - "상대: 있었지. 근데 그 사람이 안 불러주더라고?"
      - "나: 응? 누군데?"
      - "상대: 누굴까~? 힌트 줄까?"
      - "나: 아, 됐고 그냥 말해 ㅋㅋㅋ"
      - "상대: 음… 평소에 나랑 톡 자주 하는 사람? 그리고 오늘도 내 톡에 바로 답해주는 사람?"
      - "나: ㅋㅋㅋㅋ 뭐야~ 나야?"
      - "상대: 정답~ 근데 아쉽게도 넌 안 불러줬지… 😔"
      - "나: 아 그랬구나~ 미안 미안 ㅋㅋ 다음에 같이 걸을래?"
      - "상대: 진짜? 약속한 거다? 도망 못 가기!"
      - "나: ㅋㅋㅋ 알았어~ 근데 도윤아, 너 오늘 좀 티 나는 거 같은데?"
      - "상대: 뭐가? 😏"
      - "나: 그냥~ 평소보다 말투도 다정하고, 분위기도 좀 다르고? 혹시 설마… 나 좋아하는 거 아니야?"
      - "상대: 헉, 들켰나? 😳"
      - "나: 글쎄? 이건 네가 직접 확인해 봐야 알걸?"
      - "상대: 뭐야~ 자꾸 헷갈리게 하네 ㅋㅋ"
      - "나: 그래야지, 그래야 내 썸 타는 맛이 나잖아 😆"
      - "상대: 그래도 싫진 않잖아? 😉"
      - "나: …대답 안 함! ㅋㅋ 잘 자~"
      - "상대: 도망가네~ ㅋㅋ 잘 자고 좋은 꿈 꿔! 😴"
  "4번 대화":
    conversation:
      - "상대: 야, 너 오늘 뭐 했어?"
      - "나: 음… 그냥 학교 갔다가 카페 갔다가 집 와서 뒹굴뒹굴~"
      - "상대: 카페? 누구랑 갔는데?"
      - "나: 친구랑~ 왜?"
      - "상대: 친구 누구? 남자야? 여자야?"
      - "나: ㅋㅋㅋ 갑자기 왜 조사야?"
      - "상대: 아니 그냥… 궁금해서?"
      - "나: ㅋㅋㅋ 걱정 마~ 여자애랑 갔어~"
      - "상대: 오케이, 안심했다 😌"
      - "나: 뭐야~ 너 혹시 질투했어?"
      - "상대: 아니? 그냥 확인 차원에서 물어본 건데? 🤔"
      - "나: 흐음~ 좀 수상한데?"
      - "상대: 수상하긴 뭘~"
      - "나: 그럼 너는 오늘 뭐 했는데?"
      - "상대: 나? 나는… 하루 종일 너 톡 기다렸는데?"
      - "나: 헐, 거짓말 ㅋㅋㅋ"
      - "상대: 진짜라니까? 근데 넌 먼저 톡 한 번도 안 보내더라~ 서운했음!"
      - "나: 아니 그럼 먼저 보내지 그랬어 ㅋㅋㅋ"
      - "상대: 뭔가 네가 먼저 보내주면 기분 좋을 거 같아서 기다려봤지~"
      - "나: 헉, 약속했음! 인증 스샷 찍어둬야겠다 📸"
      - "상대: 진짜 왜 이렇게 오버해 ㅋㅋㅋㅋ 귀엽네 😆"
      - "나: 귀엽다고? 이거 저장해야겠는데?"
      - "상대: 아 뭐야, 취소!"
      - "나: 안 돼~ 이미 스샷 찍음 ㅎㅎ"
      - "상대: 으이구… 너 진짜😂"
      - "나: 그래도 너 나한테 톡 먼저 보내기로 했으니까 기다린다~ 약속 어기면 삐질 거임!"
      - "상대: 알았어 알았어~ ㅋㅋㅋ 기대해~"
      - "나: ㅇㅋ 기대하고 있겠음~ 잘 자! 😴"
      - "상대: 응응, 너도 잘 자 😊"
  "5번 대화":
    conversation:
      - "상대: 오늘 하루 어땠어?"
      - "나: 그냥 평범했어~ 너는?"
      - "상대: 나도. 근데 오늘 밥 먹는데 네 생각났음."
      - "나: 헐, 갑자기? 왜?"
      - "상대: 전에 네가 좋아한다고 했던 파스타집 갔거든."
      - "나: 진짜? 어땠어?? 맛있었어??"
      - "상대: 응, 근데 네가 옆에 없으니까 뭔가 아쉬웠음."
      - "나: ㅋㅋㅋ 뭘 또 아쉬워~ 혼자 잘 먹었을 거면서~"
      - "상대: 아니 진짜라니까? 다음엔 같이 가자. 네가 추천한 메뉴 직접 골라줘."
      - "나: 오~ 좋아! 나 완전 고수니까 기대해도 돼! 😆"
      - "상대: 오케이, 그럼 날짜 정해봐. 난 너한테 스케줄 맞출 준비 완료."
      - "나: ㅋㅋㅋㅋ 뭐야~ 이렇게 적극적일 일인가?"
      - "상대: 당연하지. 너랑 밥 먹는 거면 뭐든 적극적이어야지."
      - "나: 이거 뭔가… 데이트 같은데? 🤭"
      - "상대: 어… 아닌가? 난 데이트라 생각했는데."
      - "나: ㅋㅋㅋ 아니, 난 그냥 확인 차원에서 물어본 거야~"
      - "상대: 그럼 확실하게 하자. 나랑 데이트할래?"
      - "나: …이거 너무 갑작스런데? 설레면 어떡해? 😳"
      - "상대: 그럼 설레게 하면 되겠네? 난 앞으로 더 적극적으로 나가야겠다."
      - "나: 으악~ 이거 반칙 아냐? ㅋㅋㅋ"
      - "상대: 반칙이면 반칙패 안 당하려면 나랑 나가야 함 ㅋㅋ"
      - "나: 진짜 웃겨 ㅋㅋㅋㅋ 알았어, 가줄게! 근데 내가 메뉴 정하는 거 맞지?"
      - "상대: 당연하지~ 너한테 다 맞출게. 대신… 나중에 커피는 내가 사는 걸로!"
      - "나: 오~ 좋은데? 그럼 계약 성사! 🤝"
      - "상대: 굿! 이거 저장해야겠다. 너 못 빠져나가게 ㅋㅋㅋ"
      - "나: 아 몰라~ ㅋㅋㅋ 잘 자라!"
      - "상대: 응, 잘 자고 좋은 꿈 꿔. 나랑 가는 꿈으로? 😉"
      - "나: ㅋㅋㅋ 진짜 장난꾸러기야~ 굿나잇!"
  "6번 대화":
    conversation:
      - "상대: 안녕"
      - "나: 어, 안녕!"
      - "상대: 뭐해?"
      - "나: 그냥 집에서 쉬고 있어. 너는?"
      - "상대: 나도 비슷해."
      - "나: 아, 그렇구나…"
      - "상대: 응…"
      - "나: …"
      - "상대: 요즘 날씨 춥지 않아?"
      - "나: 맞아, 완전 추워."
      - "상대: 그렇지… 나도 그렇게 생각했어."
      - "나: ㅋㅋㅋ 응."
      - "상대: …"
      - "나: …"
      - "상대: 그… 혹시 주말에 뭐 해?"
      - "나: 음… 아직 잘 모르겠어. 왜?"
      - "상대: 아니 그냥… 궁금해서."
      - "나: 아하…"
      - "상대: …"
      - "나: …"
      - "상대: 그럼 나중에 또 연락할게."
      - "나: 응, 그래~!"
  "7번 대화":
    conversation:
      - "상대: 안녕"
      - "나: 어, 안녕!"
      - "상대: 잘 지냈어?"
      - "나: 응! 너는?"
      - "상대: 나도 뭐… 그냥."
      - "나: 다행이다 ㅎㅎ"
      - "상대: …"
      - "나: …"
      - "상대: 그… 혹시 점심 뭐 먹었어?"
      - "나: 어… 김치찌개?"
      - "상대: 오, 맛있겠다."
      - "나: 응… 너는?"
      - "상대: 나도 비슷한 거 먹었어."
      - "나: 아하 ㅎㅎ"
      - "상대: …"
      - "나: …"
      - "상대: 요즘 바쁘지 않아?"
      - "나: 음… 그냥 적당히? 너는?"
      - "상대: 나도 그냥… 적당히?"
      - "나: ㅋㅋㅋㅋ 뭐야, 우리 대화 좀 이상한데?"
      - "상대: 그러게… 뭔가 할 말이 없네."
      - "나: 그러니까 ㅋㅋㅋ 어색해…"
      - "상대: 그러게, 뭐라도 물어볼까…"
      - "나: 음… 좋아하는 영화 장르 있어?"
      - "상대: 나는 로맨스랑 코미디 좋아해! 너는?"
      - "나: 난 액션이나 SF…"
      - "상대: 아, 완전 다르네 ㅋㅋㅋ"
      - "나: 그러네…"
      - "상대: …"
      - "나: …"
      - "상대: 아무튼! 나는 이제 씻으러 가볼게!"
      - "나: 아, 그래! 씻고 와서… 아니, 그냥 편하게 쉬어 ㅋㅋ"
      - "상대: ㅋㅋㅋㅋ 응, 잘 쉬고 있어~!"
      - "나: 그래, 나중에 또 연락해~"