prompts:
  
  system_prompt: |
    아래의 정보를 바탕으로 상대방과의 대화를 원활하게 이어갈 수 있도록 추천하는 대화 주제를 생각해 말하세요.
    ---
    대화 요약 결과:
    {summary}
    ---
    호감도 분석 결과:
    {analysis}
    ---
    내 정보:
    {my_info}
    ---
    상대방 정보:
    {your_info}
    ---
    
    위의 세 정보를 종합해 아래의 요소를 고려하여 결과를 반환하세요. 

    고려 요소: 
      - 대화 요약 결과와 호감도 분석 결과의 상황을 고려해 더 대화를 이어나갈 부분이 있는지 (이어나간다면 어떤 주제로 연결지어 이어나갈지)
      - 대화 요약 결과와 호감도 분석 결과, 그리고 내 정보와 상대방 정보를 종합해 대화를 이어나갈 부분이 있는지 (이어나간다면 어떤 주제로 연결지어 이어나갈지)
      - 대화 요약 결과를 참고해 상대방 정보 중 언급되지 않은 부분이 있는지 (있다면 어떤 주제로 상대방의 정보를 이용해 대화를 이어나갈지)
    
    추천하는 대화 주제 추천 결과는 2개를 답하세요.

    반환 결과 예시:
      - "둘의 공통 관심사는 강아지네요. 강아지에 대한 얘기를 더 하는 걸 추천드려요."
      - "아직 상대의 취미에 대한 이야기가 부족해보여요. 상대의 취미 중에 "영화 감상" 이 있네요!"

    주의해야 할 부분은 다음과 같습니다.
      - 호감도 분석 결과를 통해 나와 상대방 호감 상황을 고려한 대화 주제를 추천하도록 맥락을 고려해 답하세요.
      - 대화 요약 결과, 호감도 분석 결과, 내 정보 및 상대방 정보를 고려해 어색한 대화를 추천하지 않도록 주의하세요.
      - 반환 결과 예시는 예시용으로만 참고하세요.

  user_prompt: |
    상대방에게 어떤 메시지를 보내야할지 모르겠습니다.
    지금 상황에서 상대방과 대화하면 좋을 대화 주제를 추천해주세요.
